### ISSUE TITLE
[Discusss] lint rules

### ISSUE THREAD

**Issue by TseHang** [visuallylab/tslint-config-frontend#1]
I just want to add two lint rules:

```
"jsx-boolean-value": ["never"],
"no-console": [true, "log"]
```

1. `jsx-boolean-value` : Do we need to add `true` when property is true ?
<img width="373" alt="螢幕快照 2019-04-02 下午3 49 02" src="https://user-images.githubusercontent.com/14778824/55385056-ddeb8f80-555e-11e9-95fa-103196a31326.png">

I think we don't need to set `true`, because it is more clean in React code. Besides, the jsx-lint in VSCode only show when there is no true.

[see react discuss](https://github.com/teamairship/tslint-react-config/issues/4)

---

2. "no-console": Could we add console in the code?
I think we can add `console.warn`, `console.error`, but we shouldn't leave `console.log` in the production. We can just ban `.log`, allow others.

<img width="569" alt="螢幕快照 2019-04-02 下午3 50 43" src="https://user-images.githubusercontent.com/14778824/55385303-62d6a900-555f-11e9-9260-41c5ba1c771f.png">

**Comment by TseHang** [comment]
According to the meeting this morning we discussed, plz @ching56 help us to improve.
Let the lint-rule go on, and try to use prettier to disable those dirty code.

**Comment by ching56** [comment]
Prettier won't handle Both `"jsx-boolean-value": ["never"]` and `"no-console": [true, "log"]`.
It means when we apply those config, both cases can exist and pass prettier, the only difference that linter is disabled for the rule.

To make coding style consistent, I would like to keep it as the same let prettier handle the jsx boolean. And open console.log linter, at least it remind us there are logs, we should remove them before production. Otherwise we probably miss them in the code review.

**Comment by TseHang** [comment]
@ching56  so could we open the `"jsx-boolean-value": ["never"]` on tslint ? or could prettier handle it ?

**Comment by ching56** [comment]
If we open the `"jsx-boolean-value": ["never"]`. Prettier won't handle it, both cases of jsx-boolean styles can exist and pass prettier, To make coding style consistent, I would like to keep the config as the same and  let prettier handle the jsx boolean as `property={true}`.

**Comment by TseHang** [comment]
Sure ~~~
so we don't do anything change on `"jsx-boolean-value"`, but open `"no-console"` to `[true, "log"]`, right?

**Comment by ching56** [comment]
I still thinks we should keep `no-console` true to make no console exist in production. 

We can ignore the linter warning at developing, but when production, 
the warning can remind us not to forget the console,
which may cause the big bottleneck if we do not remove it.

**Comment by ching56** [comment]
I was wrong, the prettier don't do anything with the rule `jsx-boolean-value`, we can turn off this rule

**Comment by TseHang** [comment]
good!
